"""Increased phone column length

Revision ID: 69682d26c80b
Revises: 497167dc3bd4
Create Date: 2025-02-03 04:44:08.988433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69682d26c80b'
down_revision = '497167dc3bd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('phone',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###
